task1: task1.cpp matmul.cpp
	g++ task1.cpp matmul.cpp -Wall -O3 -std=c++17 -o task1 -fopenmp

task2: task2.cpp convolution.cpp
	g++ task2.cpp convolution.cpp -Wall -O3 -std=c++17 -o task2 -fopenmp

task3: task3.cpp msort.cpp
	g++ task3.cpp msort.cpp -Wall -O3 -std=c++17 -o task3 -fopenmp

build: task1 task2 task3